# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  win: circleci/windows@2.4.1
# Define a job to be invoked later in a workflow
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  AcceptanceTestWindows:
    executor: win/default
    steps:
     node/install:
        node-version: "16.13.2"
         - run:
          name: Install node@16
          command: nvm install v16.13.2; nvm alias default 16.13.2
 - run:
          command: node --version
          name: Check node version
  
      - run:
          name: Install Chrome
          command: |
            $Path = $env:TEMP; $Installer = "chrome_installer.exe"; Invoke-WebRequest "http://dl.google.com/chrome/install/375.126/chrome_installer.exe" -OutFile $Path\$Installer; Start-Process -FilePath $Path\$Installer -Args "/silent /install" -Verb RunAs -Wait; Remove-Item $Path\$Installer  
      - checkout

      - run:
          name: Run Tests_engage (Windows + Integration)
          command: npm test -- --reportdir=$(Get-Date -Format "dd-MM-yyyy-HH-mm-ss") --appType=$env:APP_TYPE --testEnv=$env:TEST_ENV --testExecFile=AcceptanceNew.json  --windowWidth=1600 --windowHeight=900 --browserCapability=desktop-chrome-1920; if (-not $?) {1 > 0}
    # Invoke jobs via workflows..
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  engage:
    jobs:
      - AcceptanceTestWindows